services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: goshortsgenerator-app
    environment:
      - PORT=8080
      - STORAGE_PATH=/data
      - BGM_PATH=/assets/bgm
      - TZ=Asia/Taipei
      - AZURE_TTS_KEY=
      - AZURE_TTS_REGION=
      - GEMINI_API_KEY=
      - AI_MODEL=gemini-2.0-flash
    volumes:
      - ./data:/data
      - ./assets:/assets
